import logging
import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import markdown
from dotenv import load_dotenv
from src.utils import setup_logging

load_dotenv()
logger = setup_logging()

def send_report(report_markdown=None, recipient=None):
    """
    Sends the report via Gmail SMTP using environment variables.
    """
    if report_markdown is None:
        try:
            with open("data/report.md", "r", encoding="utf-8") as f:
                report_markdown = f.read()
        except FileNotFoundError:
            logger.error("Report file not found.")
            import sys
            sys.exit(1)

    logger.info("Preparing to send email...")
    
    if not report_markdown:
        logger.error("No report content to send.")
        import sys
        sys.exit(1)

    # Convert Markdown to HTML with custom styling
    # We will wrap the markdown output in a nice HTML template
    raw_html = markdown.markdown(report_markdown)
    
    html_body = f"""
    <html>
    <head>
        <style>
            body {{ font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f4f4f4; margin: 0; padding: 20px; }}
            .container {{ max-width: 600px; margin: 0 auto; background: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
            h1 {{ color: #1a237e; border-bottom: 2px solid #1a237e; padding-bottom: 10px; font-size: 24px; margin-top: 0; }}
            h2 {{ color: #d32f2f; font-size: 20px; margin-top: 25px; border-left: 4px solid #d32f2f; padding-left: 10px; }}
            h3 {{ color: #333; font-size: 18px; margin-top: 20px; }}
            p {{ margin-bottom: 15px; }}
            a {{ color: #1976d2; text-decoration: none; font-weight: bold; }}
            a:hover {{ text-decoration: underline; }}
            blockquote {{ background: #f9f9f9; border-left: 4px solid #ccc; margin: 10px 0; padding: 10px 15px; color: #555; font-style: italic; }}
            table {{ width: 100%; border-collapse: collapse; margin-top: 15px; font-size: 14px; }}
            th {{ background: #eee; text-align: left; padding: 8px; border-bottom: 2px solid #ddd; }}
            td {{ padding: 8px; border-bottom: 1px solid #eee; }}
            .footer {{ margin-top: 30px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 20px; }}
            .badge {{ display: inline-block; padding: 3px 8px; border-radius: 12px; background: #e3f2fd; color: #1565c0; font-size: 12px; font-weight: bold; margin-bottom: 5px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div style="text-align: center; margin-bottom: 20px;">
                <span style="font-size: 40px;">🏏</span>
            </div>
            {raw_html}
            <div class="footer">
                <p>Generated by Cricket News Agent • Powered by Gemini & GitHub Actions</p>
            </div>
        </div>
    </body>
    </html>
    """
    
    # Get credentials from environment
    sender_email = os.getenv("EMAIL_SENDER")
    password = os.getenv("EMAIL_PASSWORD")
    
    if not recipient:
        recipient = os.getenv("EMAIL_RECIPIENT", "dk5058203@gmail.com")

    # Debug logging for secrets (masked)
    if sender_email:
        logger.info(f"EMAIL_SENDER found: {sender_email[:3]}***@***")
    else:
        logger.error("EMAIL_SENDER environment variable is MISSING")

    if password:
        logger.info("EMAIL_PASSWORD found: [MASKED]")
    else:
        logger.error("EMAIL_PASSWORD environment variable is MISSING")

    if not sender_email or not password:
        logger.warning("EMAIL_SENDER or EMAIL_PASSWORD not set. Skipping actual email delivery (Simulation Mode).")
        logger.info(f"Generated HTML Content (preview):\n{html_body[:200]}...")
        # In GitHub Actions, we want to fail if secrets are missing to alert the user
        if os.getenv("GITHUB_ACTIONS"):
             logger.error("Running in GitHub Actions but secrets are missing! Failing build.")
             import sys
             sys.exit(1)
        return

    try:
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient
        msg['Subject'] = "🏏 Weekly Cricket News Report"

        msg.attach(MIMEText(html_body, 'html'))

        logger.info(f"Connecting to SMTP server for {sender_email}...")
        # Gmail SMTP configuration
        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as server:
            server.login(sender_email, password)
            server.send_message(msg)
        
        logger.info(f"Email successfully sent to {recipient}")
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        import sys
        sys.exit(1)

if __name__ == "__main__":
    send_report()


